//> using publish.organization "io.github.MaciejG604"
//> using publish.name "toolkit"
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/MaciejG604/toolkit"
//> using publish.versionControl "github:MaciejG604/toolkit"
//> using publish.developer "Maciej G||https://github.com/MaciejG604"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"

